version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:15.11.0
    working_directory: ~/OR-UK-frontend

    steps:
      - checkout
      - run: node --version
      - run: yarn install
  build:
    docker:
      - image: cimg/node:15.11.0
    working_directory: ~/OR-UK-frontend
    steps:
      - run: echo "run build task"
      - checkout
      - run: yarn install
      - run: yarn build
  deploy:
    machine:
      image: ubuntu-1604:202007-01
    working_directory: ~/OR-UK-frontend
    steps:
      - checkout
      - run: echo "deploy project"
      - run: ssh -v ${VPS_USER}@${VPS_NAME} "~/client_deploy.sh"

workflows:
  version: 2
  test-build:
    jobs:
      - build
      - test:
          requires:
            - build
     # - deploy:
      #    requires:
       #     - test
        #  filters:
         #   branches:
          #    only:
           #     - main
