version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:15.11.0
    working_directory: ~/OR-UK-frontend  
    steps:
      - checkout
      - run: node --version
      - run: echo "running tests"
      - run: npm install
      - run: npm test 
  build:
    docker:
      - image: cimg/node:15.11.0
    working_directory: ~/OR-UK-frontend    
    steps: 
      - checkout
      - run: echo "build project"
      - run: npm install
      - run: npm run build
      - run: ssh -i ${VPS_USER}@${VPS_IP} "~/client_deploy.sh" 

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - deploy:
        requires:
          - test
        filters:
          branches:
            only: main
 
